name: notification-service CI

on:
  push:
    branches: [master]
    paths:
      - "src/notification-service/**"
      - "src/notification-service-tests/**"
  pull_request:
    paths:
      - "src/notification-service/**"
      - "src/notification-service-tests/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore
        run: dotnet restore src/notification-service-tests/notification-service-tests.csproj

      - name: Test
        run: dotnet test src/notification-service-tests/notification-service-tests.csproj --no-restore --logger "console;verbosity=minimal"
